package com.company;

public class Simulation {

    public static void run(){
        Room room = new Room(1000, 30, 22,0.04);
        Machine my_intelligent_machine = new Machine(22, 30);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 21, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 19, 0.04);
        room.getLog();room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 35, 23, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 40, 25, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 21, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 19, 0.04);
        room.getLog();room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 35, 23, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 40, 25, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 21, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 19, 0.04);
        room.getLog();room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 35, 23, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 40, 25, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 21, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 19, 0.04);
        room.getLog();room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 35, 23, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 40, 25, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 21, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 19, 0.04);
        room.getLog();room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 35, 23, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 40, 25, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 21, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 19, 0.04);
        room.getLog();room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 35, 23, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 40, 25, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 21, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 19, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 35, 23, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 20, 20, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 30, 18, 0.04);
        room.getLog();
        room.plus_CO2();
        my_intelligent_machine.change(room, 40, 25, 0.04);
        room.getLog();


    }
    public static void main(String[] args) {
        Simulation.run();
    }
}
